language: java

before_install:
  - sudo add-apt-repository -y ppa:ondrej/php5
  - sudo apt-get update
  - sudo apt-get install php5 php5-dev php-pear
  - yes no | sudo pecl install yar

before_script:
    # There is no need to run this, cause now we run it in java
    #- nohup bash -c "php -ddate.timezone=PRC -dextension=yar.so -S 127.0.0.1:8095 -t src/test/resources 2>&1 &"

script:
  - mvn clean test

after_success:
  - mvn clean cobertura:cobertura coveralls:report
